// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
	export type PublicPath =
		| ""
		| "/"
		| "/background.js"
		| "/content-scripts/bridge.js"
		| "/devtools-panel.html"
		| "/devtools.html"
		| "/injected.js"
		| "/webgpu-icon.svg";
	type HtmlPublicPath = Extract<PublicPath, `${string}.html`>;
	export interface WxtRuntime {
		getURL(path: PublicPath): string;
		getURL(path: `${HtmlPublicPath}${string}`): string;
	}
}
