import type * as Monaco from "monaco-editor";

/** Monarch tokenizer for Syrup syntax highlighting. */
export const syrupMonarchLanguage: Monaco.languages.IMonarchLanguage = {
	defaultToken: "",
	tokenPostfix: ".syrup",
	keywords: [
		"let",
		"var",
		"fn",
		"struct",
		"enum",
		"case",
		"default",
		"if",
		"else",
		"guard",
		"for",
		"in",
		"while",
		"return",
		"break",
		"continue",
		"switch",
		"is",
		"class",
		"protocol",
		"do",
		"try",
		"catch",
		"throw",
		"throws",
		"init",
		"self",
		"super",
		"override",
		"mutating",
		"use",
		"from",
		"export",
		"async",
		"await",
		"declare",
	],
	constants: ["nil", "true", "false"],
	operators: [
		"->",
		"...",
		"..<",
		"?.",
		"??",
		"==",
		"!=",
		"<=",
		">=",
		"&&",
		"||",
		"+=",
		"-=",
		"*=",
		"/=",
		"=",
		"!",
		"<",
		">",
		"+",
		"-",
		"*",
		"/",
		"%",
		"?",
		":",
	],
	symbols: /[-=><!?:&|+*/%.]+/,
	tokenizer: {
		root: [
			[/\/\/.*$/, "comment"],
			[/\/\*/, "comment", "@blockComment"],
			[/@[a-zA-Z_]\w*/, "keyword"],
			[
				/[a-z_][\w]*/,
				{
					cases: {
						"@keywords": "keyword",
						"@constants": "constant.language",
						"@default": "identifier",
					},
				},
			],
			[/[A-Z][\w]*/, "type.identifier"],
			[/\$\d+/, "variable.predefined"],
			[/\d[\d_]*(\.\d[\d_]*)?([eE][+-]?\d+)?/, "number"],
			[/"/, "string", "@string"],
			[/[{}()[\]]/, "@brackets"],
			[/@symbols/, { cases: { "@operators": "operator", "@default": "" } }],
			[/[,;]/, "delimiter"],
		],
		blockComment: [
			[/[^*/]+/, "comment"],
			[/\*\//, "comment", "@pop"],
			[/[*/]/, "comment"],
		],
		string: [
			[/\$\(/, { token: "delimiter.interpolation", next: "@interpolation" }],
			[/\\./, "string.escape"],
			[/"/, "string", "@pop"],
			[/[^\\"$]+/, "string"],
			[/\$/, "string"],
		],
		// One nesting level of parens inside $( ... ) is supported.
		interpolation: [
			[/\(/, "delimiter.parenthesis", "@interpolationParen"],
			[/\)/, { token: "delimiter.interpolation", next: "@pop" }],
			{ include: "@interpolationCommon" },
		],
		interpolationParen: [
			[/\(/, "delimiter.parenthesis", "@interpolationParen"],
			[/\)/, "delimiter.parenthesis", "@pop"],
			{ include: "@interpolationCommon" },
		],
		interpolationCommon: [
			[
				/[a-z_][\w]*/,
				{
					cases: {
						"@keywords": "keyword",
						"@constants": "constant.language",
						"@default": "identifier",
					},
				},
			],
			[/[A-Z][\w]*/, "type.identifier"],
			[/\$\d+/, "variable.predefined"],
			[/\d[\d_]*(\.\d[\d_]*)?([eE][+-]?\d+)?/, "number"],
			[/"/, "string", "@string"],
			[/@symbols/, { cases: { "@operators": "operator", "@default": "" } }],
			[/[,;[\]{}]/, "delimiter"],
		],
	},
};
